// Generated by Flutter gen-l10n. Do not edit.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appTitle => 'GixGiz';

  @override
  String get appMarkSemanticLabel => 'GixGiz application mark';

  @override
  String get foundationNavigationLabel => 'Foundation';

  @override
  String get aboutNavigationLabel => 'About';

  @override
  String get foundationTitle => 'Foundation';

  @override
  String get aboutTitle => 'About GixGiz';

  @override
  String get loadingTitle => 'Checking foundation';

  @override
  String get loadingMessage =>
      'GixGiz is checking whether the local core is available.';

  @override
  String get readyPlaceholderTitle => 'Presentation placeholder';

  @override
  String get readyPlaceholderMessage =>
      'A future verified core response can render here. This shell has not verified local AI readiness.';

  @override
  String get notConnectedTitle => 'Core not connected';

  @override
  String get notConnectedMessage =>
      'This foundation build contains the desktop shell only. Local AI setup is not available yet.';

  @override
  String get degradedTitle => 'Core connection degraded';

  @override
  String get degradedMessage =>
      'The desktop received a limited core status. Check again before continuing.';

  @override
  String get failedTitle => 'Foundation check failed';

  @override
  String get failedMessage =>
      'GixGiz could not check the local core. Review diagnostics, then try again.';

  @override
  String get cancelledTitle => 'Foundation check cancelled';

  @override
  String get cancelledMessage =>
      'The check was cancelled. No system changes were made.';

  @override
  String get checkAgainAction => 'Check again';

  @override
  String get diagnosticsLabel => 'Diagnostics';

  @override
  String diagnosticCodeLabel(String code) {
    return 'Diagnostic code: $code';
  }

  @override
  String foundationStatusSemanticLabel(String status, String detail) {
    return 'Foundation status: $status. $detail';
  }

  @override
  String get loadingProgressSemanticLabel => 'Foundation check progress';

  @override
  String get inProgressSemanticValue => 'In progress';

  @override
  String get aboutSummary => 'Local-first desktop foundation';

  @override
  String get releaseLabel => 'Release';

  @override
  String get applicationIdLabel => 'Application ID';

  @override
  String get coreConnectionLabel => 'Local core';

  @override
  String get coreNotConnectedValue => 'Not connected in this build';
}
