// Generated by Flutter gen-l10n. Do not edit.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appTitle => 'GixGiz';

  @override
  String get appMarkSemanticLabel => 'GixGiz application mark';

  @override
  String get foundationNavigationLabel => 'Foundation';

  @override
  String get aboutNavigationLabel => 'About';

  @override
  String get foundationTitle => 'Foundation';

  @override
  String get aboutTitle => 'About GixGiz';

  @override
  String get loadingTitle => 'Checking foundation';

  @override
  String get loadingMessage =>
      'GixGiz is checking whether the local core is available.';

  @override
  String get coreReadyTitle => 'Platform core ready';

  @override
  String get coreReadyMessage =>
      'The authenticated Rust platform core is available.';

  @override
  String get notConnectedTitle => 'Core not connected';

  @override
  String get notConnectedMessage =>
      'The local platform core is unavailable. Check again before continuing.';

  @override
  String get missingCoreTitle => 'Core component missing';

  @override
  String get missingCoreMessage =>
      'The bundled Rust core could not be found. Repair or reinstall GixGiz, then try again.';

  @override
  String get startupTimedOutTitle => 'Core startup timed out';

  @override
  String get startupTimedOutMessage =>
      'The local core did not complete its secure startup in time. Close GixGiz and try again.';

  @override
  String get connectionLostTitle => 'Core connection lost';

  @override
  String get connectionLostMessage =>
      'The authenticated local connection ended unexpectedly. Check again to reconnect.';

  @override
  String get protocolMismatchTitle => 'Core update required';

  @override
  String get protocolMismatchMessage =>
      'The desktop and bundled core use incompatible protocol versions. Repair or update GixGiz.';

  @override
  String get authenticationFailedTitle => 'Core authentication failed';

  @override
  String get authenticationFailedMessage =>
      'The secure local session could not be authenticated. Restart GixGiz to create a new session.';

  @override
  String get degradedTitle => 'Core connection degraded';

  @override
  String get degradedMessage =>
      'The desktop received a limited core status. Check again before continuing.';

  @override
  String get failedTitle => 'Foundation check failed';

  @override
  String get failedMessage =>
      'GixGiz could not check the local core. Review diagnostics, then try again.';

  @override
  String get cancelledTitle => 'Foundation check cancelled';

  @override
  String get cancelledMessage =>
      'The check was cancelled. No system changes were made.';

  @override
  String get checkAgainAction => 'Check again';

  @override
  String get diagnosticsLabel => 'Diagnostics';

  @override
  String diagnosticCodeLabel(String code) {
    return 'Diagnostic code: $code';
  }

  @override
  String foundationStatusSemanticLabel(String status, String detail) {
    return 'Foundation status: $status. $detail';
  }

  @override
  String get loadingProgressSemanticLabel => 'Foundation check progress';

  @override
  String get inProgressSemanticValue => 'In progress';

  @override
  String get coreApplicationLabel => 'Application';

  @override
  String get coreVersionLabel => 'Core version';

  @override
  String get protocolVersionLabel => 'Protocol';

  @override
  String get readinessLabel => 'Readiness';

  @override
  String get unknownValue => 'Unknown';

  @override
  String coreDetailsSemanticLabel(
    String application,
    String version,
    String protocol,
    String readiness,
  ) {
    return 'Core details: application $application, version $version, protocol $protocol, readiness $readiness';
  }

  @override
  String get aboutSummary => 'Local-first desktop foundation';

  @override
  String get releaseLabel => 'Release';

  @override
  String get applicationIdLabel => 'Application ID';

  @override
  String get coreConnectionLabel => 'Local core';

  @override
  String get coreNotConnectedValue => 'Not connected in this build';
}
