// Generated by Flutter gen-l10n. Do not edit.
import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:intl/intl.dart' as intl;

import 'app_localizations_en.dart';

// ignore_for_file: type=lint

/// Callers can lookup localized strings with an instance of AppLocalizations
/// returned by `AppLocalizations.of(context)`.
///
/// Applications need to include `AppLocalizations.delegate()` in their app's
/// `localizationDelegates` list, and the locales they support in the app's
/// `supportedLocales` list. For example:
///
/// ```dart
/// import 'l10n/app_localizations.dart';
///
/// return MaterialApp(
///   localizationsDelegates: AppLocalizations.localizationsDelegates,
///   supportedLocales: AppLocalizations.supportedLocales,
///   home: MyApplicationHome(),
/// );
/// ```
///
/// ## Update pubspec.yaml
///
/// Please make sure to update your pubspec.yaml to include the following
/// packages:
///
/// ```yaml
/// dependencies:
///   # Internationalization support.
///   flutter_localizations:
///     sdk: flutter
///   intl: any # Use the pinned version from flutter_localizations
///
///   # Rest of dependencies
/// ```
///
/// ## iOS Applications
///
/// iOS applications define key application metadata, including supported
/// locales, in an Info.plist file that is built into the application bundle.
/// To configure the locales supported by your app, you’ll need to edit this
/// file.
///
/// First, open your project’s ios/Runner.xcworkspace Xcode workspace file.
/// Then, in the Project Navigator, open the Info.plist file under the Runner
/// project’s Runner folder.
///
/// Next, select the Information Property List item, select Add Item from the
/// Editor menu, then select Localizations from the pop-up menu.
///
/// Select and expand the newly-created Localizations item then, for each
/// locale your application supports, add a new item and select the locale
/// you wish to add from the pop-up menu in the Value field. This list should
/// be consistent with the languages listed in the AppLocalizations.supportedLocales
/// property.
abstract class AppLocalizations {
  AppLocalizations(String locale)
    : localeName = intl.Intl.canonicalizedLocale(locale.toString());

  final String localeName;

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  /// A list of this localizations delegate along with the default localizations
  /// delegates.
  ///
  /// Returns a list of localizations delegates containing this delegate along with
  /// GlobalMaterialLocalizations.delegate, GlobalCupertinoLocalizations.delegate,
  /// and GlobalWidgetsLocalizations.delegate.
  ///
  /// Additional delegates can be added by appending to this list in
  /// MaterialApp. This list does not have to be used at all if a custom list
  /// of delegates is preferred or required.
  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates =
      <LocalizationsDelegate<dynamic>>[
        delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ];

  /// A list of this localizations delegate's supported locales.
  static const List<Locale> supportedLocales = <Locale>[Locale('en')];

  /// No description provided for @appTitle.
  ///
  /// In en, this message translates to:
  /// **'GixGiz'**
  String get appTitle;

  /// No description provided for @appMarkSemanticLabel.
  ///
  /// In en, this message translates to:
  /// **'GixGiz application mark'**
  String get appMarkSemanticLabel;

  /// No description provided for @foundationNavigationLabel.
  ///
  /// In en, this message translates to:
  /// **'Foundation'**
  String get foundationNavigationLabel;

  /// No description provided for @aboutNavigationLabel.
  ///
  /// In en, this message translates to:
  /// **'About'**
  String get aboutNavigationLabel;

  /// No description provided for @foundationTitle.
  ///
  /// In en, this message translates to:
  /// **'Foundation'**
  String get foundationTitle;

  /// No description provided for @aboutTitle.
  ///
  /// In en, this message translates to:
  /// **'About GixGiz'**
  String get aboutTitle;

  /// No description provided for @loadingTitle.
  ///
  /// In en, this message translates to:
  /// **'Checking foundation'**
  String get loadingTitle;

  /// No description provided for @loadingMessage.
  ///
  /// In en, this message translates to:
  /// **'GixGiz is checking whether the local core is available.'**
  String get loadingMessage;

  /// No description provided for @readyPlaceholderTitle.
  ///
  /// In en, this message translates to:
  /// **'Presentation placeholder'**
  String get readyPlaceholderTitle;

  /// No description provided for @readyPlaceholderMessage.
  ///
  /// In en, this message translates to:
  /// **'A future verified core response can render here. This shell has not verified local AI readiness.'**
  String get readyPlaceholderMessage;

  /// No description provided for @notConnectedTitle.
  ///
  /// In en, this message translates to:
  /// **'Core not connected'**
  String get notConnectedTitle;

  /// No description provided for @notConnectedMessage.
  ///
  /// In en, this message translates to:
  /// **'This foundation build contains the desktop shell only. Local AI setup is not available yet.'**
  String get notConnectedMessage;

  /// No description provided for @degradedTitle.
  ///
  /// In en, this message translates to:
  /// **'Core connection degraded'**
  String get degradedTitle;

  /// No description provided for @degradedMessage.
  ///
  /// In en, this message translates to:
  /// **'The desktop received a limited core status. Check again before continuing.'**
  String get degradedMessage;

  /// No description provided for @failedTitle.
  ///
  /// In en, this message translates to:
  /// **'Foundation check failed'**
  String get failedTitle;

  /// No description provided for @failedMessage.
  ///
  /// In en, this message translates to:
  /// **'GixGiz could not check the local core. Review diagnostics, then try again.'**
  String get failedMessage;

  /// No description provided for @cancelledTitle.
  ///
  /// In en, this message translates to:
  /// **'Foundation check cancelled'**
  String get cancelledTitle;

  /// No description provided for @cancelledMessage.
  ///
  /// In en, this message translates to:
  /// **'The check was cancelled. No system changes were made.'**
  String get cancelledMessage;

  /// No description provided for @checkAgainAction.
  ///
  /// In en, this message translates to:
  /// **'Check again'**
  String get checkAgainAction;

  /// No description provided for @diagnosticsLabel.
  ///
  /// In en, this message translates to:
  /// **'Diagnostics'**
  String get diagnosticsLabel;

  /// No description provided for @diagnosticCodeLabel.
  ///
  /// In en, this message translates to:
  /// **'Diagnostic code: {code}'**
  String diagnosticCodeLabel(String code);

  /// No description provided for @foundationStatusSemanticLabel.
  ///
  /// In en, this message translates to:
  /// **'Foundation status: {status}. {detail}'**
  String foundationStatusSemanticLabel(String status, String detail);

  /// No description provided for @loadingProgressSemanticLabel.
  ///
  /// In en, this message translates to:
  /// **'Foundation check progress'**
  String get loadingProgressSemanticLabel;

  /// No description provided for @inProgressSemanticValue.
  ///
  /// In en, this message translates to:
  /// **'In progress'**
  String get inProgressSemanticValue;

  /// No description provided for @aboutSummary.
  ///
  /// In en, this message translates to:
  /// **'Local-first desktop foundation'**
  String get aboutSummary;

  /// No description provided for @releaseLabel.
  ///
  /// In en, this message translates to:
  /// **'Release'**
  String get releaseLabel;

  /// No description provided for @applicationIdLabel.
  ///
  /// In en, this message translates to:
  /// **'Application ID'**
  String get applicationIdLabel;

  /// No description provided for @coreConnectionLabel.
  ///
  /// In en, this message translates to:
  /// **'Local core'**
  String get coreConnectionLabel;

  /// No description provided for @coreNotConnectedValue.
  ///
  /// In en, this message translates to:
  /// **'Not connected in this build'**
  String get coreNotConnectedValue;
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(lookupAppLocalizations(locale));
  }

  @override
  bool isSupported(Locale locale) =>
      <String>['en'].contains(locale.languageCode);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

AppLocalizations lookupAppLocalizations(Locale locale) {
  // Lookup logic when only language code is specified.
  switch (locale.languageCode) {
    case 'en':
      return AppLocalizationsEn();
  }

  throw FlutterError(
    'AppLocalizations.delegate failed to load unsupported locale "$locale". This is likely '
    'an issue with the localizations generation tool. Please file an issue '
    'on GitHub with a reproducible sample app and the gen-l10n configuration '
    'that was used.',
  );
}
